default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: furima_46195_development
  host: localhost
  username: postgres
  password: postgres123
  # ↑これはローカル開発用なのでそのままでもOK（必要なら自分の環境に合わせる）

test:
  <<: *default
  database: furima_46195_test
  host: localhost
  username: postgres
  password: postgres123

production:
  url: <%= ENV["DATABASE_URL"] %>
